# SPDX-FileCopyrightText: 2023 Adafruit Industries
#
# SPDX-License-Identifier: MIT

# This is where you store the credentials necessary for your code.
# The associated demo only requires WiFi, but you can include any
# credentials here, such as Adafruit IO username and key, etc.
# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="3L3V4T3D"
CIRCUITPY_WIFI_PASSWORD="N4wT4UBu1m4"

# To enable modifying files from the web. Change this too!
# Leave the User field blank when you type the password into the browser.
CIRCUITPY_WEB_API_PASSWORD="P455w0rd"
CIRCUITPY_WEB_API_PORT=80

# Bluetooth enable
# CIRCUITPY_BLE_NAME="MatrixPortal"

# Timezone
CIRCUITPY_TIMEZONE="America/Chicago"